name: example

dependencies:
  flutter:
    sdk: flutter
  flutter_i18n:
    path: ../
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/

environment:
  sdk: '>=1.19.0 <3.0.0'